### ISSUE TITLE
iOS 13 Support

### ISSUE THREAD

**Issue by olegbarinov** [ImKcat/CatCrypto#8]
## Environment
- CatCrypto: 0.3.0
- Xcode: 11.0 beta 5
- iOS: 13.0 beta 6

## Reproduce steps
1. Build a project.

## Description
Swift Compiler Error:
- Redefinition of module 'CommonCrypto' (iPhoneSimulator13.0.sdk/usr/include/CommonCrypto/module.modulemap:1:8)
- Could not build Objective-C module 'CommonCryptoFramework' (CatCrypto/Sources/Core/Crypto.swift:23:8)

**Comment by rajivshah3** [comment]
Does using the latest commit on `master` help? This was probably fixed in https://github.com/ImKcat/CatCrypto/pull/5

**Comment by olegbarinov** [comment]
@rajivshah3 If it's present in current version (0.3.0), then no, it does not help.

**Comment by rajivshah3** [comment]
I think it hasn't been released yet, but you can point your Podfile to a certain commit

**Comment by olegbarinov** [comment]
@rajivshah3 Just checked with the latest commit, it works. Hope you release it soon.

**Comment by imkcat** [comment]
@olegbarinov Sorry for the delay response, the new version is released.
