### ISSUE TITLE
Argon random uint8 salt

### ISSUE THREAD

**Issue by librehome** [ImKcat/CatCrypto#9]
## Issue type

- [X ] Bug
- [X ] Feature
- [ ] Question

<!--

## Environment

- CatCrypto: 0.2.3
- Xcode: 9.0
- iOS: 8.0

Argon2 only takes string as salt, which breaks when salt is [UInt8], can you add this feature/fix?

Thanks a lot

**Comment by imkcat** [comment]
Please provide more details
